### ISSUE TITLE
Problems with cloning repo 

### ISSUE THREAD

**Issue by artrayme** [ostis-apps/ostis-geography#29]
There are some files with ':' symbol in the name. For example, "problem-solver/py/modules/street_translator_module/specification/showcase)/showcase_1.png:Zone.Identifier"

But this file naming is not supported on Windows. So I can't clone this repository on Windows.

![image](https://user-images.githubusercontent.com/78550819/194715236-4718804a-9052-442f-8b61-9b4568b386a2.png)

**Comment by NikitaZotov** [comment]
Fixed
